### ISSUE TITLE
Screen stuck after completing configuration

### ISSUE THREAD

**Issue by N4TU5** [ranenbg/Arduino-FFB-gui#11]
Hello. When I launch the wheel_control app on the bottom left for quite some time it says "Configuring wheel control". Then after couple of minutes it changes to "" and stays like it without loading anything else. I have tried re-downloading it from github but it didn't help.
If I try to run it manually using processing I get errors "frame cannot be resolved to a variable" in multiple files. What could cause this and what can I do to try and resolve it?
![image](https://github.com/user-attachments/assets/c9f7a3da-ff8a-477d-b93d-197770c48d0e)
![image](https://github.com/user-attachments/assets/80456fdc-330a-4af5-a0f1-cc727cfcbb8f)

**Comment by N4TU5** [comment]
Update:
I'm having problem with v232ZHX. I just tried with v230... and everything works, it launches quickly and without any issues. However I want to use load cell so I would like to use v232 :/

**Comment by ranenbg** [comment]
Hi, tnx for reporting this issue, I see it for the first time.

From info that you provided, it seems like something might be wrong with that particulair HEX version. For some reason, an empty string is returned as a response where GUI expects to read firmware configuration parameters, after sending command "U" to it. Do you have HX711 connected to arduino? You don't need to have load cell connected to HX711 at this point, but this chip has to be connected correctly to arduino, or the firmware may get stuck while trying to communicate with it. When you plug arduino to USB port, give it some time before you start GUI, because firmware for load cell needs to do tare zeroing which takes 2 seconds. It is not required to have encoder connected at this point. It is useful to have ffb indicator led connected (see encoder wiring diagram). At every arduino powerup led will quickly blink 3 times after finishing initial config if everything is ok.

For every new firmware release, I'm manualy compiling 30+ HEX files, where I set by hand all options and version string. It's possible that I made some mistake with that particulair one. I'll have to check it myself in more details when I get some free time. If everything is fine with your arduino, hx711 and wiring, but the issue still persits it could be that I just need to recompile that HEX again. It is worth to download lattest firmware release again, as I did recently recompile some HEX files.

In the meantime, if you wish to help, you may also do some troubleshooting using Arduino IDE and serial monitor. Set 115200 baud rate and carriage return as string terminator, then send command V, response should be v232zhx. After that, try command U, response should be several numbers. You can check this also with v230 (or any other HEX). You can find a full list of all available commands in RS232commands_info.txt file.

**Comment by N4TU5** [comment]
Hey. Thank you for the response! That's on me, I didn't think you need to have HX711 connected on startup, as it does work without any other inputs connected (encoder, potentiometers, buttons). I only tried it with HX711 once and now after first check with my multimeter it looks like there are some problems with my HX711 wiring. I will attempt to fix the wiring and try it again.

I'm closing this issue for now as I'm guessing fixing the wiring should resolve my problems
