### ISSUE TITLE
could i use one of the potentiometer to control the ffb ?  

### ISSUE THREAD

**Issue by Eyadserry** [ranenbg/Arduino-FFB-gui#15]
I was wondering if I could set a potentiometer to control the general gain.

**Comment by ranenbg** [comment]
Hi, at the moment I have no such feature in the firmware. However, a very simple modification is required in order to achieve it. General gain is a global variable and you simply have to map it to the pot value instead of axis value, just bare in mind that you will be sacrificing one analog input for it. I leave this as an excercise to you. Let me know if you have any difficuilties along the way.

**Comment by Eyadserry** [comment]
I'm still beginner in programing so it's a long way.
