### ISSUE TITLE
black screen gui

### ISSUE THREAD

**Issue by madhack2142** [ranenbg/Arduino-FFB-gui#9]
hello got this problem, black screen in wheel control, tried to create com_cfg with com number same result
tried to connect arduino leo to pc without usbhub, no luck 
tried different firmware, no changes
noticed that wheel_control create a lot of javaw.exe after launch in task manager 
![image](https://github.com/ranenbg/Arduino-FFB-gui/assets/114923875/099c5a65-e73b-40ab-8449-623c0d02edb7)

**Comment by ranenbg** [comment]
Hi, at this point all looks normal to me. I see that the pink screen is empty, nothing is connected. You need to get this done once and it should start normaly. I have described the procedure in manual.txt, in data folder of wheel control. In that folder you can also find a png example of pink window with all connections. Once you make all lines (connections), you have to click verify and then if no errors, click use. I think you missed this step. Once you complete it you don't have to do it anymore, it's a one time setup only.

Give it a go first and let me know if you can start wheel control.

**Comment by madhack2142** [comment]
![image](https://github.com/ranenbg/Arduino-FFB-gui/assets/114923875/28a9746b-c052-4821-9577-8a054d2de807)
![image](https://github.com/ranenbg/Arduino-FFB-gui/assets/114923875/8672b3d3-a2f7-44cc-983e-9c22863e65a9)

wires already checked, axis have intense shaking

this problem happens on my laptop and i have no idea why, on pc i manually write port in comcfg and it works normal : ffb. axis
i tried to install new java 21 & 8

**Comment by ranenbg** [comment]
Hi, it seems that you did not understand me. You keep missing a vital setup step. The images you posted again, the pink window is not completed, as there are no lines connected. You have clicked verify and it gave you 30 errors, because you didn't make a single connection between table on the left and the table on the right. Without this, wheel control setup can't complete. You have to do it once on every PC. Pink window should look exactly like this, no crossings between lines, and all items must be connected.

![Wheel_control_gamecontrols_setup](https://github.com/ranenbg/Arduino-FFB-gui/assets/34513854/eb7036c7-ad36-499f-af1f-ac1a7495eb2b)

You have to read manual.txt and documentation I have provided. I repeat, I've provided and example of pink window with all connections done correctly, you have to look at it. It will save both of us time and unneccesary texting.

**Comment by madhack2142** [comment]
i managed to solve my issue, tried arduino leonardo/promicro, got 24 or 25 errors when i have connected all buttons in software, a bit later decided to switch to brWheel_my.ino.leonardo_v230.hex without any letters at end and after connecting buttons it works flawlessly. noticed that on main pc there is no setup window step with buttons, application immediately crash after pressing OK, need to add device to comcfg manually and it starts normally

**Comment by ranenbg** [comment]
Hi, I'm glad you managed to sort it out.

Just please, make sure to use the latest wheel control GUI v2.6.0. You need it in order to utilize the full feature support of Arduino firmware HEX v230.
